FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm base systemd

# set up boot
RUN pacman -S --nocnofirm linux linux-firmware mkinitcpio systemd-boot

# set up gui
RUN pacman -S --noconfirm pantheon lightdm lightdm-pantheon-greeter

# common tools
RUN pacman -S --noconfirm bash zsh vim

# locale
RUN echo "en_GB.UTF-8 UTF-8" >> /etc/locale.gen
RUN locale-gen

# timezone
RUN ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
RUN echo "Europe/London" > /etc/timezone

# set up network
RUN pacman -S --noconfirm networkmanager
RUN systemctl enable NetworkManager

# set up user
RUN pacman -S --noconfirm sudo
RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN useradd -m -G wheel -s /bin/zsh ***REMOVED*** 
RUN echo "***REMOVED***:***REMOVED***" | chpasswd
