#!/bin/sh

if command -v buildah >/dev/null 2>&1; then
  BUILD_ENGINE="buildah"
elif command -v docker >/dev/null 2>&1; then
  BUILD_ENGINE="docker"
elif command -v podman >/dev/null 2>&1; then
  BUILD_ENGINE="podman"
else
  echo "No build engine found"
  exit 1
fi

if [ -z "$1" ]; then
  echo "Using default path '.'"
  set -- "."
fi

SUCC_PATH="/succ"
IMAGES_PATH="${SUCC_PATH}/images"

mkdir -p "${SUCC_PATH}"
mkdir -p "${IMAGES_PATH}"

n=1
while [ -d "${IMAGES_PATH}/${n}" ] ; do
  n=$(expr $n + 1)
done
REVISON=$n

echo "Building revision ${REVISON}"

ROOT_PATH="${IMAGES_PATH}/${REVISON}"

mkdir -p "${ROOT_PATH}"

if ! ${BUILD_ENGINE} build -t the-image -o type=local,dest="${ROOT_PATH}" $1; then
  echo "Build failed"
  rm -rf "${ROOT_PATH}"
  exit 1
fi