#!/bin/sh

IMAGES_PATH="/succ/images"

n=1
while [ -d "${IMAGES_PATH}/${n}" ] ; do
  if [ $(stat -c %i "${IMAGES_PATH}/${n}") -ne $(stat -c %i "/") ] ; then
    echo "Removing ${IMAGES_PATH}/${n}"
    rm -rf "${IMAGES_PATH}/${n}"
  fi
  n=$(expr $n + 1)
done